mholt/archiver

targz.go
zip.go
zip_test.go

Currently, while decrompressing (extracting files), if any are a symbolic link, archiver will fail. This change adds in support for the tar(gz) format to open, and create tar archives with symbolic links.
Zip files, do not support symbolic links, but this update does allow them to exist, merely skipping over them. There appears to be an issue with zip files and symbolic links.
This change, also preserves the file mode, and chmod according to original file mode. (Not applicable on Windows build)
Working on testing this. Currently the included tests attempt to compress, decompress all the files in test data. I need to write a test that will prevent zip files from messing with the symbolic links.

add support for symbolic links and preserve file mode.

---

tarbz2.go

The github.com/dsnet/compress packages now require a ReaderConfig
or WriterConfig to be passed in to NewReader or NewWriter.
A nil Config is guaranteed to always pass.

Update tarbz2.go to account for recent API changes

---

targz.go

`tar.TypeRegA` should be cared. 
Following code doesn't work with Error `pt_linux_amd64/pt: unknown type flag:`.
```go
package main
import (
"fmt"
"io"
"net/http"
"os"
"path"
"github.com/mholt/archiver"
)
func main() {
url := "https://github.com/monochromegane/the_platinum_searcher/releases/download/v2.1.2/pt_linux_amd64.tar.gz"
resp, _ := http.Get(url)
defer resp.Body.Close()
fname := path.Base(url)
f, _ := os.Create(fname)
io.Copy(f, resp.Body)
err := archiver.UntarGz(fname, "pt")
if err != nil {
fmt.Println(err.Error())
}
}
```
This patch resolve it.

can't `UntarGz` some archives

---

rar.go

While trying to unrar an archive with subfolders, the call to header.IsDir evaluates as false because the folder structure does not exist yet. This is a less than ideal way to parse the path for subfolders and create them as needed before header.IsDir is checked against.

parsing header.Name (filepath) for subfolders

---

targz.go
zip.go

When file is in use and size getting increased , create compressed file will failed and error is "copying contents: archive/tar: write too long".  Changing to use CopyN to copy only the file size at that time,  also checks io.EOF if file becomes small.

fix copying contents: archive/tar: write too long

---

zip.go

Please use filepath.Dir(), not path.Dir().
In Windows, following code doesn't work with Error
`peco_windows_amd64\peco_windows_amd64\Changes: creating new file: open peco_windows_amd64\peco_windows_amd64\Changes: The system cannot find the path specified.`
```
package main
import (
"fmt"
"io"
"net/http"
"os"
"path"
"github.com/mholt/archiver"
)
func main() {
url := "https://github.com/peco/peco/releases/download/v0.4.0/peco_windows_amd64.zip"
resp, _ := http.Get(url)
defer resp.Body.Close()
fname := path.Base(url)
f, _ := os.Create(fname)
io.Copy(f, resp.Body)
err := archiver.Unzip(fname, "peco_windows_amd64")
if err != nil {
fmt.Println(err.Error())
}
}
```
And following code doesn't extract .tar.gz file including symlink with Error: `dest\hoge.txt: creating new file: open dest\hoge.txt: …

use filepath.Dir() instead of path.Dir()

---

zip.go

`zip.FileHeader.Name` is documented to be a `/`-separated path,
rather than an `os.PathSeparator`-separated file system path:
// Name is the name of the file.
// It must be a relative path: it must not start with a drive
// letter (e.g. C:) or leading slash, and only forward slashes
// are allowed.
Source: https://godoc.org/archive/zip#FileHeader.Name
Therefore, it's correct to use `path.Join` rather than `filepath.Join`
when setting its value. Package [path](https://godoc.org/path) manipulates and produces
slash-separated paths, while package [filepath](https://godoc.org/path/filepath) manipulates and
produces `os.PathSeparator`-separated file system paths.
Updates https://github.com/mholt/archiver/pull/9#issuecomment-241184865.

Use path.Join when setting zip.FileHeader.Name.

---

archiver.go
tar.go

This was necessary for extracting [the FreeBSD base system](http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/11.0-RELEASE/base.txz).

Add hard link support

---

archiver_test.go
rar.go
tar.go
tarbz2.go
targz.go
tarxz.go
zip.go

This adds an archive format identification by checking a file's header, which is commented as Todo in `Match` methods in each format codes. But despite this, `Match` method still prefers a file extension identification to this and uses this only when a file doesn't have an expected extension so its behavior would not change so much.
There are a few more points should be noted
- Added methods only return `bool` value, without an error value not to change `Match` method interface
- Added methods don't care if a passed `filename` is actually accessible or not and if not, they silently return `false`

Identify archive format from file header

---

tar.go

Character devices, block devices and named pipes have the separate types, but at the same time they can be extracted like the other files and they're handled well by archive/tar library. Supporting these headers is necessary for extracting Linux rootfs archives.

tar: Add TypeChar, TypeBlock and TypeFifo header flags support

---

zip.go

In Windows, zipping a directory such as:
```
a\
b\
file
```
Results in an archive that looks like this:
```
a\
b\
\file
```
(notice how "file" is prefixed by a slah)
This is caused by the usage of strings.TrimPrefix to make a path relative. strings.TrimPrefix doesn't ensure the removal of trailing slashes and it will leave a backward trailing slash untouched. I fixed the problem by using filepath.Rel instead.
I hope this helps other folks using/deploying applications to Windows.
Thanks for this awesome library mholt ;-)

Zip.Make: fixed path bug in windows

---

zip.go

When compress a folder contains subdirectory to zip on windows and then uncompress on *nix, the files in subdirectory will in a flatten level. Its' unexpected.

Fix zip header name with wrong sep

---

rar.go

rardecode has a method called `OpenReader` which should act the same as NewReader, but also supports multipart rar files.
This shouldn't cause any issues or undesired side effects, it just skips the `os.Open` call and passes the path directly to the rardecode package.

Add support for multipart rar files

---

archiver.go
archiver_test.go
rar.go
tar.go
tarbz2.go
targz.go
tarlz4.go
tarsz.go
tarxz.go
zip.go

1. Adds methods to interface.
2. Implement methods for each format.
3. Reimplement Make/Open so that code is shared.
This intended to implement a solution to issue #20.

Add Read and Write methods to Archiver interface that accept io.Reader/io.Writer.

---

archiver.go
cmd/archiver/main.go

This is intended to solve issue #44.

Add MatchingFormat function to archiver package and refactor main.go to use it.

---

archiver.go
cmd/archiver/main.go
rar.go
tar.go
zip.go

This PR is meant to fix an arbitrary file write vulnerability, that can be achieved using a specially crafted zip archive, that holds path traversal filenames. When the filename gets concatenated to the target extraction directory, the final path ends up outside of the target folder. 
A sample malicious zip file named zip-slip.zip. (see [this gist](https://gist.github.com/grnd/2992cc4d968386ae277123bad9e7f00a)) was used, and when running the code below, resulted in creation of `evil.txt` file in /tmp folder.
```go
package main
import "log"
import "github.com/mholt/archiver"
func main() {
err := archiver.Tar.Open("/tmp/evil-tar.tar", "/tmp/safe")
if err != nil {
log.Fatal(err)
}
}
```
There are various possible ways to avoid this issue, some include checking for `..` (dot dot) characters …

fix: prevent extraction of archived files outside target path

---

tar.go

Due to inactivity on https://github.com/mholt/archiver/pull/66
Closes https://github.com/mholt/archiver/issues/27
Satisfies https://github.com/mholt/archiver/pull/66#issuecomment-398922536 (tests not necessary)
Signed-off-by: Nikki Attea <nikki@sensu.io>

Ignore the pax global header from git generated tarballs

---

rar.go

#43 broke the support for multi-part rar files that was added in #38 (due to `rardecode.OpenReader()` not being used anymore). This PR fixes that!

Add back support for multipart rar files

---

tar.go

I have stumbled onto issue similar to this #62, while creating tar archive on Windows and trying to build Docker (Linux based) image of it. I have found this PR #64 and adjusted the changes.
Seems like it fixed the issue.

Fix setting tar FileInfoHeader name

---

archiver.go
archiver_test.go

There are a number of ways to get this done, the one this PR does was the least amount of change and close to where this was introduced; The other option would be to change all Open functions to process the destination string through the filepath.Clean before it sends it downstream.

Fixes #82 by processing destination string through filepath.Clean

---

archiver.go
tar.go
tarbz2.go
targz.go
tarlz4.go
tarsz.go
tarxz.go
zip.go

There is no functional difference for existing code, only the additional function `Archiver.CheckExt(string) error` which can be used to validate file extensions for Archiver interface types.
As for stylistic choices, I wasn't too sure whether I should return the error immediately, wrap it (like I have done) or create a new error. The implementation I chose retains the original functionality whilst also matching the `CheckExt(string) error` return values in the `Compressor` interface. It's fortunate that the error strings are formatted to let me do it like this.
Also I was worried about a name-clash causing confusion/compile errors with the `Compressor.CheckExt(string) error` function, so let me know if you think I should change it.

Implement CheckExt(string) error for Archiver interface

---

.travis.yml
appveyor.yml

The old URL will start breaking when the import path is being enforced in Go 1.12+
https://github.com/golang/lint/commit/c67002cb31c3a748b7688c27f20d8358b4193582

Use canonical URL for golint

---

appveyor.yml
archiver.go
archiver_test.go
tar.go
testdata/exist
testdata/proverb3.txt
zip.go

Also implement extraction of symlinks from zip archives.
This PR also adds a relative symlink in the testdata directory. It passes all tests on OS X, but has not been tested on Windows.
This PR is a superset of changes from the following issues and PRs:
Fixes #21 
Fixes #31 
Fixes #60 
Fixes #74

Add support for storing symlinks in tar and zip archives

---

archiver.go

The function `writeNewFile()` overwrites the file if it already exists.
Following the same behavior, modified `writeNewSymbolicLink()` and
`writeNewHardLink()` to do the same.
Referencing this issue:
https://github.com/mholt/archiver/issues/143

Unlink symbolic and hard links if they already exists while extracting

---

go.mod
go.sum

I found a bug in the encoder where it in rare cases would output an extra byte if input is mod 2MB - and only when using the `io.ReaderFrom` interface, which is done by `io.Copy` and when input doesn't support `io.WriterTo`... *phew*
Fix is in latest version of the compress library.

Upgrade zstd encoder

---

zip.go

7z seems to have adopted a different strategy to create ZIP+lzma. 
Here also fixes archive ls panic, unsupported compression method panic

Disable ZIP+LZMA

---

.goreleaser.yml
.prettierrc
README.md
cmd/arc/main.go

- add `version` subcommand
- add `goreleaser` with bare binaries
- cleanup `README.md` with `prettier`
- add `webi` as install method
- clarify manual build and install instructions
Updated README can be previewed at https://github.com/mholt/archiver/tree/goreleaser
`goreleaser` is typically used with `tar` and `zip` but, being that we might assume the person that wants to install `arc` may not have that support on their system, it may make sense to not compress and package it.
~This may rely on https://github.com/goreleaser/goreleaser/pull/1821 and  https://github.com/goreleaser/goreleaser/pull/1823~
That said, Linux and Unix (Darwin) systems that I've encountered have GUI and CLI `tar.xz` support built-in, and Windows 10 has zip support both in the GUI and CLI (both in BSD tar.exe and …

Updates for Releases ( and Goreleaser )

---

zstd.go

Fixes: https://github.com/mholt/archiver/issues/183
Allows setting of any encoder or decoder options when imported.
In the referenced issue `zstd.WithDecoderLowmem(false)` could be set for example.

Add exported encoder/decoder opts for zstd

---

cmd/arc/main.go
testdata/create-evil-zip.go
zip.go

This improves the performance over the stdlib implementation.
Archiving seems to be about 2.5x faster in my tests and archiving seems to be around 1.2x faster.
Those numbers should be even better after https://github.com/mholt/archiver/pull/272 is merged with the updated of the compression library.

Switch zip handling to use github.com/klauspost/compress/zip

---

tar.go
zip.go

This will make it easier for user's of this library (like me :) ) to filter out the different underlying errors and handle them.
For more information, see:
https://blog.golang.org/go1.13-errors

Use go error wrapping for easier error handling

---

tar.go
zip.go

Followup on #276 
I now get errors like these:
`path/to/file: making header: write tcp 10.2.0.6:8080->10.99.12.11:52284: write: broken pipe`
I would like to filter these too :)

Use go error wrapping on header writing for easier error handling

---

rar.go

I think that was a typo, since the bytes in the byte slice even say "Rar", so I guess it is a rar specific header being checked here.

Change hasTarHeader to hasRarHeader in rar.go

---

go.mod
go.sum

v1.0.1 of the package was retracted due to occasional panics and data
corruption, see
https://github.com/andybalholm/brotli/commit/5376c15dde3fd4247febd5a3b4ac9708d2d6faff

Update github.com/andybalholm/brotli to v1.0.4

---

fs.go
interfaces.go
rar.go
tar.go
zip.go

Motivated by https://github.com/rclone/rclone/issues/2815.
Allows creating an archive by sending files down a channel rather than needing to pre-build a list of all the files up front. This is useful for efficiently creating an archive when reading a sequential stream. I think.

Add ArchiveAsync; context no longer optional

---

archiver.go
archiver_test.go
fs.go

Now permit suffixing root on disk with separator to enumerate only
its contents and not to create that actual file in archive.
And attempt improving Windows compatibility. I don't have Windows handy so this'll have to be CI-based feedback.
@nicola-spb could you give this a try?

Enhance FilesFromDisk (close #331)

---

fs.go

Should fix #334 :man_shrugging:

fs: Improve Open and Stat on ArchiveFS for streams

---

7z.go

add Archive method to SevenZip

---

zip.go

The zip.Extract method creates a closure for the File.Open function
pointer sent to the handler method.
Unfortunately it uses the same File for each call to the handler
function which means that if the caller stores the File objects and
uses them after Extract has returned then each File.Open function
pointer will open the same object.
This is easily fixed by making sure that each iteration of the Extract
loop uses a new File variable.

zip: fix File.Open not working if called after zip.Extract completes

---

formats.go
tar.go

This PR contains two commits
- Allow Identify to take a nil io.Reader
Allow Identify to take a nil io.Reader
The Match functions can all take a nil io.Reader to mean just identify
the archive from its file name, but before this patch Identify could
not.
This patch allows the stream to be nil, and enables Identify to be
used to create formats for archives which haven't been created yet
just from their file name.
- Fix crash when Tar.Match is given a nil stream

Allow Identify to take a nil io.Reader

---

formats.go
interfaces.go
tar.go
zip.go

This PR contains two commits
- Rework ArchiveAsync interface to make it return any archiving errors
After experience with the current ArchiveAsync interface while
creating an rclone backend it became clear that it wasn't quite right.
With the old interface, callers did not know when the File had been
archived and thus did not know when to release resources associated
with that file.
This patch changes the interface so that it returns the error
archiving each File. This means the caller can know when the File has
been archived and when to release resources. It returns the error for
each file archived which is useful too.
Fixes #368
- Add ArchiveAsync support to CompressedArchive

Rework ArchiveAsync interface to make it return any archiving errors

---

formats_test.go
zlib.go

Added a test to demonstrate a bug in the `Identify` routine where the zlib format incorrectly matches on ASCII files starting with the letter x (because ASCII x is the same as the first expected `byte` for ZlibHeader).
Unsure of how best to address.
The ZlibHeader match could be expanded to look at the second byte and verify it is one of the accepted values associated with the different compression levels.
Or could try and decompress the first part of the file using zlib? Not sure how robust that is, or how much you would need to read...maybe something like the following?
```
func (zz Zlib) Match(filename string, stream io.Reader) (MatchResult, error) {
var mr MatchResult
// match filename
if strings.Contains(strings.ToLower(filename), zz.Name()) {
mr.ByName = true
}
// match file header …
```

zlib format incorrectly matches on ASCII files starting with the letter x

---

tar.go

* add NumericUid and NumericGid to Tar struct
* writeFileToArchive: set Uname and Gname to empty string if NumericUid and NumericGid are true, respectively.

Option to use number for user and/or group names

---

archiver.go

Fix https://github.com/mholt/archiver/issues/387

Fix create archive to a continuous writing source file failed

---

7z.go

7z: Fix iteration bug that was already fixed in go 1.22.
The bug is same as https://github.com/mholt/archiver/blob/master/zip.go#L199

7z: Fix iteration bug

---

.github/workflows/macos-latest.yml
.github/workflows/ubuntu-latest.yml
.github/workflows/windows-latest.yml
README.md
formats_test.go
go.mod
go.sum
lzip.go

Add lzip support

---

gz.go

Somewhat related to #405, it turns out that `compress/gzip` has a feature to handle trailing data without returning an error.
> If you would like the ability to read a valid gzip member and specially handle non-gzip data after the member, then you can use the [gzip.Reader.Multistream](https://pkg.go.dev/compress/gzip#Reader.Multistream) feature to read the file one member at a time.
> 
> https://github.com/golang/go/issues/47809
I created a field called `DisableMultistream` and not `Multistream` because `gzip.Reader.Multistream` is enabled by default. The latter would silently disable `Multistream` for any existing instances of `archiver.Gz{}`. 
**Additional Context**
https://github.com/trufflesecurity/trufflehog/issues/2934

Expose gzip.Reader.Multistream

---

go.mod
go.sum
lzip.go

This reverts commit a902fcc00a188fb940b75bb3db65a2cb44636a58.
See also #421.

chore(go.mod): Switch to upstream lzip package

---

go.mod
go.sum

This includes a fix for a potential panic.
See: https://github.com/nwaples/rardecode/issues/36#issuecomment-2408530176

Upgrade rardecode to v2.0.0-beta.3
